development:
  adapter: postgresql
  encoding: unicode
  database: GremlinBooks_development
  pool: 5
  username: postgres
  password: abc123

test:
  adapter: postgresql
  encoding: unicode
  database: GremlinBooks_test
  pool: 5
  username: postgres
  password: abc123

production:
  adapter: postgresql
  encoding: unicode
  database: GremlinBooks_production
  pool: 5
  username: postgres
  password: abc123

