  amazon:
    vendor_name: 'Amazon'
    access_key: 'AKIAJGEEG4RCTCF2DCHQ'
    secret_key: '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'
    associate_tag: 'wwwgremlinboo-20'
    affiliate_percent: 6
  chegg:
    vendor_name: 'Chegg'
    key: '1522fa5538fd041d8855c507ac1bf6a5'
    base_url: 'http://api.chegg.com/rent.svc'
    password: '4190344'
    affiliate_percent: 6
    aid: 'AID'
    pid: '7045869'
    sid: 'SID'
  book_byte:
    vendor_name: 'Book Byte'
    auth_token: 'Lk1YwBqGUVIa4QOOcNT6oA=='
    publisher_id: 'K620292'
    base_url: 'http://webservices.bookbyte.com/rest/v1/getinventoryprice.aspx'
    affiliate_percent: 6
  book_renter:
    vendor_name: 'Book Renter'
    developer_key: 'FqRlncrCJCxKKaRwQaphKGKiH4mNWwdf'
    base_url: 'http://www.bookrenter.com/api/fetch_book_info'
    affiliate_percent: 6
  commission_junction:
    website_id: 7208985
    auth_key: '00b18d488889010d9f0176f59a2777cc296a56f575ed4c60009640d9af3f2ed449a0d21b3e679c8a91f86feb0936ba39518552541da59ba373f8b573b7b76d3539/1ac9d647c364054a184e7a7fe7b48b7934322a96c056e5a5310657d1b916b7b0a3abd613937ca76f2ae0d542988eea0fcbd03a15475deebc6a85a305e5c59a01'
    base_url: 'https://product-search.api.cj.com/v2/product-search'