  amazon:
    vendor_name: 'Amazon'
    access_key: 'AKIAJGEEG4RCTCF2DCHQ'
    secret_key: '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'
    associate_tag: 'wwwgremlinboo-20'
    affiliate_percent: 6
  chegg:
    vendor_name: 'Chegg'
    key: '1522fa5538fd041d8855c507ac1bf6a5'
    base_url: 'http://api.chegg.com/rent.svc'
    password: '4190344'
    affiliate_percent: 6
    aid: 'AID'
    pid: 'PID'
    sid: 'SID'
  book_byte:
    vendor_name: 'Book Byte'
    auth_token: 'Lk1YwBqGUVIa4QOOcNT6oA=='
    publisher_id: 'K620292'
    base_url: 'http://webservices.bookbyte.com/rest/v1/getinventoryprice.aspx'
    affiliate_percent: 6
  book_renter:
    vendor_name: 'Book Renter'
    developer_key: 'FqRlncrCJCxKKaRwQaphKGKiH4mNWwdf'
    base_url: 'http://www.bookrenter.com/api/fetch_book_info'
    affiliate_percent: 6